### ISSUE TITLE
[bug] GitHub Actions build_examples.py output not showing up

### ISSUE THREAD

**Issue by formatc1702** [formatc1702/WireViz#100]
After testing #94, I realized that the output images referenced to in the [main readme](https://github.com/formatc1702/WireViz/blob/feature/multicolor-wires-2/README.md) as well as the example and tutorial galleries (`readme.md` in the [respective](https://github.com/formatc1702/WireViz/tree/feature/multicolor-wires-2/examples) [directories](https://github.com/formatc1702/WireViz/tree/feature/multicolor-wires-2/tutorial)) are no longer showing up on GitHub in the feature branch.

I am not familiar with GitHub actions, but if I understand correctly, the new addition from a3f2134ed15125be9cdb8a6353994375b8b9c92f...

```yaml
    - name: Upload examples, demos, and tutorials
      uses: actions/upload-artifact@v2
      with:
        name: examples-and-tutorials
        path: |
          examples/
          tutorial/
```

is meant to work as follows:
- Before commiting/pushing, the user runs `python build_examples.py clean` to remove any PNG, SVG, GV and other output files as well as the two readme's to keep the repo clean 👍 
- after pushing to GitHub, this Action is supposed to generate the examples and readmes, and add them to the repo again?

Either I am misunderstanding, or it's not working; the fact is that the current system is broken.
Where exactly do the files uploaded by this action end up?

Perhaps @aakatz can explain what's going on, and maybe @flopp (who implemented the initial GitHub Actions workflow) knows something about this topic? Thanks!
