### ISSUE TITLE
[internal] Proposal: shorten BOM part number attributes

### ISSUE THREAD

**Issue by formatc1702** [formatc1702/WireViz#114]
I propose shortening the part number attributes from
```yaml
    manufacturer: ABC
    manufacturer_part_number: 123
    internal_part_number: 456
```
to
```yaml
    pn: 456
    mpn: 123
    manufacturer: ABC
```

MPN seems to be an industry standard abbreviation.
Also, they are [currently rendered](https://github.com/formatc1702/WireViz/blob/dev/tutorial/tutorial08.png) as `MPN` and `IPN` anyway.

I propose `pn` over `ipn` in the YAML, and rendering it as `P/N: ` in the output, but that's up for debate.

@Tyler-Ward (and others, of course) any thoughts?

[Edit]
As a side note, I would also like to swap the order of the fields in the graphic output to match the above:
`P/N: 456 | MPN: 123 | ABC`
