### ISSUE TITLE
[proposed feature] Netlist input/output

### ISSUE THREAD

**Issue by aakatz3** [formatc1702/WireViz#124]
It would be nice to have an output and/or input for some form of EDA type netlist, whether in SPICE type format, Protel/Altium format, Kicad format, eagle format, etc.

If people want this feature, I can investigate to see which format is the best.

**Comment by formatc1702** [comment]
I hadn't thought of any EDA tool integration (could you describe a specific usecase for this?) but a sort of netlist output has been on my mind.

Simply a table of signals within the harness, and a listing of which wires and connector pins are carrying this signal, would be quite useful when the wiring diagram gets a bit more complex and individual wires harder to follow.

Example output shown as YAML for readability>
```yaml
signals:
  GND:
    - X1: [1, 3]
    - W1: [1, s]
    - X2: [1]
  VCC:
    - X1: [2]
    - W1: [2]
    - X2: [2]
  ```
