### ISSUE TITLE
[feature] Add ferrule before connector

### ISSUE THREAD

**Issue by stmaxted** [formatc1702/WireViz#134]
It would be nice to be able to specify a wire requires a ferrule before being put into a connector. I'm think of the case where someone wants to do something like:
![IMG_20200729_160207](https://user-images.githubusercontent.com/17870845/88755337-0c11cb80-d1b5-11ea-9afe-fd1ad271de78.jpg)

**Comment by kvid** [comment]
Maybe PR #115 could be a solution for this request?

**Comment by formatc1702** [comment]
My gut feeling also is to specify the ferrules as additional BOM items (as per #115)...

otherwise, you would need to define a connection between two connectors directly, with no wire inbetween, which (at least currently) is not possible _by design_. I'm not saying it's impossible, though... the connection from ferrule to the actual connector could be graphically represented as a thin, dashed line, for example, or even an arrow, to make it clear that it's not a physical wire linking the two.

🤔

**Comment by stmaxted** [comment]
Adding additional lines to the BOM would work nicely. 
However the mockup looks very similar to what I was thinking of.

**Comment by kvid** [comment]
> otherwise, you would need to define a connection between two connectors directly, with no wire inbetween, which (at least currently) is not possible _by design_.
> I'm not saying it's impossible, though... the connection from ferrule to the actual connector could be graphically represented as a thin, dashed line, for example, or even an arrow, to make it clear that it's not a physical wire linking the two.

One way this could be specified, is to use `<-`, `--`, or `->` instead of a cable/wire between two connectors in a `connections` entry to indicate a direct connection without wires between, and the arrow direction can be used to indicate male to female connection like in the mockup above with a possible input YAML like this:
```yaml
connectors:
  X1:
    pincount: 4
    type: Screw terminal connector
    color: GN
  F1:
    style: simple
    autogenerate: true
    type: Ferrule
    color: GY

cables:
  W1:
    gauge: 0.25 mm2
    length: 1
    color: BK
    colors: [BK, WH, BU, BN]

connections:
  -
    - X1: [1-4]
    - <-
    - F1
    - W1: [1-4]
```
Such an implementation would also fix #148 to enable a harness that is split with mating connectors, and would help implementing #142 as well.

**Comment by formatc1702** [comment]
I was thinking of having a separate section in the YAML file.
`connections` could remain unchanged, for strict connector-cable-connector-[...] sequences.
A new section, `mates` or similar, could define mechanical matings such as the one suggested above, as well as #142 and #148. It could define pinwise mates (such as the four ferrules above going into different pins on the connector), or simple connector to connector mates, where all pins are linked 1-to-1, without having one explicit arrow for each (this would look insane on high-pincount connectors)...

**Comment by formatc1702** [comment]
Renamed issue title to consolidate with #148.

**Comment by MSBGit** [comment]
This is a common situation that I run into, where I want to specify that one connector must plug into another connector. I haven't been able to figure out a good way to do this other than using a naming convention for both connectors. Ideally _wireviz_ would allow me to specify this type of connection and somehow render it so it's obvious to the person looking at the wiring diagram:
![con-con](https://user-images.githubusercontent.com/5497625/96817983-677ae080-13d5-11eb-89b4-852ae66ebcaa.jpg)

**Comment by formatc1702** [comment]
> One way [a mate between two connectors] could be specified, is to use `<-`, `--`, or `->` instead of a cable/wire between two connectors in a `connections` entry to indicate a direct connection without wires between, and the arrow direction can be used to indicate male to female connection like in the mockup above [...]

>  It could define pinwise mates (such as the four ferrules above going into different pins on the connector), or simple connector to connector mates, where all pins are linked 1-to-1, without having one explicit arrow for each (this would look insane on high-pincount connectors)...

One idea would be:
- use `<-`, `--`, `->`, `<->` to display a single dashed line/arrow between two components (e.g. when mating male and female connectors of one series)
  ```yaml
  connections:
    -
      - X1
      - <-
      - X2
  ```

  The issue will be that currently, listing a designator without appending a pin list (`- X1`) is the syntax used for auto-generation of connectors, so we would need a way to differentiate the two use-cases, or come up with a new syntax for this case. The first idea that comes to mind is using an empty pinlist:
  ```yaml
  connections:
    -  # mating two connectors
      - X1: []  # empty pinlist: join the connectors themselves, not individual pins!
      - <-
      - X2: []
    -  # defining the connection of X2's pins to other wires etc. in a separate connection set
      - X2: [1-4]
      - W99: [1-4]
      # etc. 
  ```

- use `<=`, `==`, `=>`, `<=>` to display one dashed line/arrow for each pin in the connection set (e.g. for @stmaxted's ferrule example)
  ```yaml
  connections:
    -
      - X1: [1-4]
      - <=
      - F1
  ```

  I don't see any issue with this use-case, except forbidding the use of `<=` et.al. as user-assigned designators, which shouldn't be too bad as a restriction.

---

A full example using two complementary connectors from @stmaxted's original photo could look like this:
```yaml
connectors:
  X1: &X
    type: Screw connector
    subtype: female
    color: GN
    pincount: 4
  X2:
    <<: *X
    subtype: male
  F:
    style: simple
    autogenerate: true
    type: Ferrule
    color: GY

cables:
  W1: &W
    colors: [BK, WH, BU, BN]
  W2:
    <<: *W

connections:
  -  # ferrules + connector X1
    - W1: [1-4]
    - F
    - =>
    - X1
  -  # mate X1 and X2
    - X1: []
    - ->
    - X2: []
  -  # ferrules + connector X2
    - X2
    - <=
    - F
    - W2: [1-4]
```
