### ISSUE TITLE
Allow pin out to be numbered

### ISSUE THREAD

**Issue by opolanco23** [formatc1702/WireViz#138]
Hello,

If this is already a feature if you could point me in the right direction that would be awesome. 

I have a 26 pin molex connector where only 5 pins are used, so I would like to show which pins of the 26 are actually used. If just describe the pin out its interpreted as there are only 5 pins if I manually add the pin count then I do not know how to specify which of the 26 are used. 

```
type: automotive
    subtype: male
    pincount: 26
    pinout: [GA-NET+, AMP, RCA+, GA-NET-, RCA-]
    notes: GA-NET(BUS) has 68 ohm 1/2 watt resistor
```

could something like this be used

```
pincount: 26
pinout:
   pin20: AMP
```

and any pins not mentioned are assumed blank? If there is already something like this then I apologize and please show me an example.

**Comment by kvid** [comment]
> Hello,
> 
> If this is already a feature if you could point me in the right direction that would be awesome.
> 
> I have a 26 pin molex connector where only 5 pins are used, so I would like to show which pins of the 26 are actually used. If just describe the pin out its interpreted as there are only 5 pins if I manually add the pin count then I do not know how to specify which of the 26 are used.
> 
> ```
> type: automotive
>     subtype: male
>     pincount: 26
>     pinout: [GA-NET+, AMP, RCA+, GA-NET-, RCA-]
>     notes: GA-NET(BUS) has 68 ohm 1/2 watt resistor
> ```
> 
> could something like this be used
> 
> ```
> pincount: 26
> pinout:
>    pin20: AMP
> ```
> 
> and any pins not mentioned are assumed blank? If there is already something like this then I apologize and please show me an example.

Perhaps not exactly what you want, but you could try using `NC` or `-` for unused pins until your last used pin in the `pinout` and `hide_disconnected_pins` like in this (slightly modified [example 07](https://github.com/formatc1702/WireViz/tree/master/examples#example-07)):
```yaml
# contributed by @elliotmr

connectors:
  X1:
    type: TE 776164-1
    subtype: female
    hide_disconnected_pins: True
    pincount: 35
    pinout: [NC,-,-,-,AA,BB]
    notes: Unconnected pins are not shown

  X2:
    type: D-Sub
    subtype: female
    pincount: 9
    pinout: [NC,B,-,-,-,-,A]
    hide_disconnected_pins: True
    notes: Unconnected pins are not shown

cables:
  C1:
    wirecount: 2
    gauge: 20 AWG
    colors: [YE, GN]
    length: 1

connections:
  -
    - X1: [5,6]
    - C1: [1,2]
    - X2: [7,2] 
```
![ex07+pinout](https://user-images.githubusercontent.com/12657033/88940263-d853a600-d287-11ea-81c7-0ae4093625f6.png)

**Comment by kvid** [comment]
> I have a 26 pin molex connector where only 5 pins are used, so I would like to show which pins of the 26 are actually used. If just describe the pin out its interpreted as there are only 5 pins if I manually add the pin count then I do not know how to specify which of the 26 are used.
> 
> ```
> type: automotive
>     subtype: male
>     pincount: 26
>     pinout: [GA-NET+, AMP, RCA+, GA-NET-, RCA-]
>     notes: GA-NET(BUS) has 68 ohm 1/2 watt resistor
> ```

Based on your your connector info (assuming which 4 pin numbers you are using other than pin 20) and my last alternative in my comment above, I got this:
```yaml
connectors:
  Molex1:
    type: automotive
    subtype: male
    pincount: 26
    pinnumbers: [19,20,21,22,23]
    pinout: [GA-NET+, AMP, RCA+, GA-NET-, RCA-]
    notes: GA-NET(BUS) has 68 ohm 1/2 watt resistor

cables:
  Cable1:
    wirecount: 5
    color_code: DIN

connections:
  -
    - Molex1: [19-23]
    - Cable1: [1-5]
```
![issue138](https://user-images.githubusercontent.com/12657033/88945468-50bd6580-d28e-11ea-9386-2322675654d5.png)
