### ISSUE TITLE
[bug] Referencing pin labels with '-' when defining connections

### ISSUE THREAD

**Issue by formatc1702** [formatc1702/WireViz#139]
Discovered on a modified version of the example from #138.

When using the `-` character in a pin label, and then referencing this pin label in `connections`, the character is interpreted to be a range of pins, rather than part of the pin label itself.

```yaml
connectors:
  Molex1:
    type: automotive
    subtype: male
    pincount: 26
    pins: [19,20,21,22,23]
    pinlabels: [GA-NET+, AMP, RCA+, GA-NET-, RCA-]
    notes: GA-NET(BUS) has 68 ohm 1/2 watt resistor

cables:
  Cable1:
    wirecount: 5
    color_code: DIN

connections:
  -
    - Molex1: [GA-NET+, GA-NET-]
    - Cable1: [1-2]
```

In the second to last line, `GA-NET+` is interpreted as a range from `GA` to `NET+`, and an error is thrown.
```
ValueError: invalid literal for int() with base 10: 'GA'
```

The example works when replacing all `-` in `pinlabels` with `_` or other.

The parsing should be modified to check for existing labels first, before calling `wv_helper.expand()`
OR
`wv_helper.expand()` should be made smarter.
