### ISSUE TITLE
"|" character in pinout results in misaligned table

### ISSUE THREAD

**Issue by KarolNi** [formatc1702/WireViz#157]
```
connectors:
  X1:
    type: xxxx
    pinout: [Yy, Zz]
  X2:
    type: aaaaa
    pinout: [Bb,Cc|Dd,Ee]

cables:
  W1:
    gauge: 1 AWG
    length: 1
    wirecount: 2
    category: bundle

connections:
  -
    - X1: [1,2]
    - W1: [1,2]
    - X2: [1,2]
```
![bug](https://user-images.githubusercontent.com/24433835/90897636-bc927a00-e3c5-11ea-8102-e3b158ab7878.png)

Also please consider adding "-v" arg to print version number - my according to pip is 0.1
