### ISSUE TITLE
[feature] Accept optional (and overridable) harness attribute(s)

### ISSUE THREAD

**Issue by kvid** [formatc1702/WireViz#158]
There is a `Harness.color_mode` attribute that is not currently possible to specify from the YAML input file, and additional similar attributes might be needed later.

How should such an attribute be specified in the YAML input?
```yaml
harness:
  color_mode: SHORT
```
or without a section:
```yaml
color_mode: SHORT
```
or some other way?

What's the recommended way to allow specifying a value for such an attribute in a prepended YAML file, and optionally override the value in the main harness YAML file?
```yaml
# Prepended preferences.yml file
harness: &harness_preferences
  color_mode: SHORT

# Main harness.yml file
harness:
  <<: *harness_preferences
  color_mode: HEX
```
or without a section:
```yaml
# Prepended preferences.yml file
color_mode: SHORT

# Main harness.yml file
color_mode: HEX
```
or some other way?

**Comment by kvid** [comment]
- Maybe `file_out` and `output_formats` also are harness attribute candidates to obtain what is suggested in https://github.com/formatc1702/WireViz/issues/60#issuecomment-663681078?
- `input_language` might be a future candidate as suggested in https://github.com/formatc1702/WireViz/issues/135#issuecomment-665624510.

**Comment by formatc1702** [comment]
There might be some more metadata fields that could fit into this section.
Especially when generating a proper technical drawing with a title block (see [example](https://user-images.githubusercontent.com/2447251/86395695-f639e500-bca0-11ea-9070-7a926e2cf12b.png) from in #32 / #74), a few things come to mind:
```
metadata:
  title: Main power harness
  pn: 123-456-789
  created:
    author: J. Doe
    date: 2020-01-01
  approved:
    author: X. Yz
    date: 2020-02-02
  revisions:
    01:
      description: Add ferrules
      author: J. Doe
      date: 2020-03-03
    02:
      ...
  notes: |
    This could be a multiline
    string that appears somewhere
    on the page.
```

I don't know if this kind of metadata about the harness should be mixed with rendering parameters such as the originally proposed `color_mode`, `output_formats` etc. but it's worth considering.

**Comment by kvid** [comment]
> There might be some more metadata fields that could fit into this section.
> Especially when generating a proper technical drawing with a title block (see [example](https://user-images.githubusercontent.com/2447251/86395695-f639e500-bca0-11ea-9070-7a926e2cf12b.png) from in #32 / #74), a few things come to mind:
> 
> ```
> metadata:
>   title: Main power harness
>       ...
>   notes: |
>     This could be a multiline
>     string that appears somewhere
>     on the page.
> ```
> 
> I don't know if this kind of metadata about the harness should be mixed with rendering parameters such as the originally proposed `color_mode`, `output_formats` etc. but it's worth considering.

- Some metadata entries are useful in more than output, e.g. `title`, `author`, `date` and `notes` in both HTML and technical drawing output. Maybe all metadata can be included in both of these outputs?

- Rendering options like `Harness.color_mode` and `Harness.mini_bom_mode` (suggested in #115) and other options suggested above might fit into a group called `options`:
```yaml
metadata:
  title: Main power harness
  ...
options:
  color_mode: HEX
  mini_bom_mode: False
connectors:
  ...
cables:
  ...
connections:
  ...
```
