### ISSUE TITLE
[bug] Pin case sensitivity. 

### ISSUE THREAD

**Issue by zombielinux** [formatc1702/WireViz#160]
I'm looking at implementing this but I use a lot of mil-circ connectors. 

As such, they typically run A-Z, then a-z, then I think aa-zz.

As it stands, defining the template:
```
   - &MS3126F18-32P
     type: MS3126F18-32P
     pins: [A, B, C, D, E, F, G, H, J, K, L, M, N, P, R, S, T, U, V, W, X, Y, Z, a, b, c, d, e, f, g, h, j]
```
And then using pin "a" actually connects pin "A". In my case, these are VERY different pins. This is with the latest dev branch.

**Comment by kvid** [comment]
Thank you for reporting this bug. It seems WireViz is case sensitive about identifiers, but unfortunately Graphviz is not. This means a similar problem occurs when a connector/cable name is not case insensitive unique.

I suggest keeping WireViz case sensitive to allow use cases like yours, but appending a unique numeric suffix to those identifiers that are not case insensitive unique (or to all identifiers to simplify the implementation) when writing the identifiers to the `.gv` file (e.g. A_0 and a_1 in your case), except when used as pure text output (i.e. hiding these identifier suffixes for the user).

**Comment by formatc1702** [comment]
Here's a quick test that displays the observed behavior:
```
connectors:
  X1:
    pins: [AA, Aa, aA, aa]
  X2:
    pins: [ZZ, Zz, zZ, zz]

cables:
  W1:
    wirecount: 1

connections:
  -
    - X1: AA
    - W1: 1
    - X2: zz
    # expected result: link AA to zz
    # actual result:   link aa to zz
```
