### ISSUE TITLE
[Feature] Allow referencing a cable's/bundle's wires by color or label, if unambiguous

### ISSUE THREAD

**Issue by formatc1702** [formatc1702/WireViz#193]
Similar to how a connector's pins can be referenced by its ID (as per its entry in `pins`), or by its label (as per its entry in `pinlabels`) in case the label is unambiguous, a cable's/bundle's wire needs the ability to be referenced by its color (if unambiguous) since that is often the most natural way for the user. Additionally, cables should have a `wirelabels` attribute analogous to a connector's `pinlabels`, that can also be used for referencing.

[Example 08](https://github.com/formatc1702/WireViz/tree/master/examples#example-08)'s connection set should therefore work with either of the following:

- Using the wire numbers (currently the only way):
  ```yaml
  connections:
    -
      - Key: [S,R,T]
      - W1: [1,2,3]
  ```

- Using the wire colors:
  ```yaml
  connections:
    -
      - Key: [S,R,T]
      - W1: [WH, BN, GN]
  ```

- Using the new `wirelabels` attribute:
  ```yaml
  ...
  
  cables:
    W1:
      color_code: DIN
      wirecount: 3
      wirelabels: [one, two, three]
      ...
  
  connections:
    -
      - Key: [S,R,T]
      - W1: [one, two, three]
  ```
