### ISSUE TITLE
[bug] Leading zero in string fields interpreted as octal

### ISSUE THREAD

**Issue by JelmerT** [formatc1702/WireViz#213]
**Issue:** 
when using an `int` with a leading zero in the `mpn` or any other field, the number gets interpreted as an octal number.

**How to reproduce:**
This
```
  X2:
    type: "Picoblade 1.25MM \nOr Equivalent"
    pn: 0510210600
    mpn: 0510210600
    manufacturer: MOLEX
    subtype: female
    pins: [6,5,4,3,2,1]
    pinlabels: [+5v, Data Request, Data GND, NC, Data, Power GND]
```
compiles into this
![Screen Shot 2021-01-27 at 12 42 54](https://user-images.githubusercontent.com/873684/106051418-4513f580-609d-11eb-9b90-728ef523d1ca.png)

Note the different product numbers.

This is an issue that's very easy to miss and could result in the wrong part being selected.

Fixes could be to allow `int` and `str` for these fields, and make sure they get interpreted correctly, or to throw an error if an `int` is input where a `str` is expected.
