### ISSUE TITLE
[bug] A connector with no wires connected is not handled correctly

### ISSUE THREAD

**Issue by kvid** [formatc1702/WireViz#217]
1. The `graphviz.backend` raises an exception when processing a harness including a connector with neither `pinlabels`, nor `pincolors`, and no wires connected. This is clearly a bug. See also variations of this bug below.
```yaml
connectors:
  Simple:
    pincount: 2
```
2. A connector in the harness with `pinlabels` or `pincolors`, but without any wires connected is rendered with all pin numbers hidden. I cannot see the rationale behind this. There are use cases where unconnected connectors make sense, e.g. documenting mating connectors, or when documenting connector pinout of one or more connectors is the sole purpose.
```yaml
connectors:
  HiddenPins:
    pinlabels: [+5V, GND]
```
3. An exception is raised when processing a harness including a connector with `pinlabels` or `pincolors`, and internal `loops`, but no ordinary wires connected. This is also clearly a bug. Documenting a loop-back connector is then impossible, but can be useful in similar use cases as above.
```yaml
connectors:
  Loopback:
    pinlabels: [IN, OUT]
    loops:
      - [1, 2]
```
