### ISSUE TITLE
[bug] ℃ cannot be printed

### ISSUE THREAD

**Issue by tszabooatIMT** [formatc1702/WireViz#22]
Defining working temperature is not possible. It is printed as either â„ƒ or Â°C depending on which character is used. Looks like an UTF coding problem. Maybe it could be defined in an other way, like parameter?

**Comment by kvid** [comment]
Could you provide a YAML input file and an output file that shows this problem? I tried to append `40°C` to the connector type in ex05.yml and my case all output files showed the temperature as expected without any extra characters.
`    type: Molex KK 254 40°C`
![ex05](https://user-images.githubusercontent.com/12657033/85856895-18bb9200-b7b9-11ea-8cef-05e8d51f5ef3.png)

**Comment by tszabooatIMT** [comment]
![example](https://user-images.githubusercontent.com/67461257/85857561-671d6080-b7ba-11ea-8325-5369e7241ee9.png)

connectors:
  X1:
    type: example2
    subtype: RA
    pinout: [A,B,C,D]
  X2:
    type: example1
    subtype: RA
    pinout: [VP, Rxd/TxD-N, DGND, Rxd/TxD-N]

cables:
  W1:
    gauge: 0.25 mm2
    length: 1
    colors: [RD, WH, BK, GN]
    notes: Working temperature -40°C  +60°C (fixed installation), 500Vrsm AC voltage rating
connections:
  -
    - X1: [1,2,3,4]
    - W1: [1,2,3,4]
    - X2: [1,2,3,4]

**Comment by kvid** [comment]
Your YAML input did not survive completely in your last posting. Try the "Insert code" button (look for <> in the toolbar) and check the result with "Preview" when you need to keep spacing/indentation, etc. However, I tried to reconstruct it into valid syntax (please verify my reconstruction below against your input file): 
```
connectors:
  X1:
    type: example2
    subtype: RA
    pinout: [A,B,C,D]
  X2:
    type: example1
    subtype: RA
    pinout: [VP, Rxd/TxD-N, DGND, Rxd/TxD-N]

cables:
  W1:
    gauge: 0.25 mm2
    length: 1
    colors: [RD, WH, BK, GN]
    notes: Working temperature -40°C +60°C (fixed installation), 500Vrsm AC voltage rating

connections:
  -
    - X1: [1,2,3,4]
    - W1: [1,2,3,4]
    - X2: [1,2,3,4]
```
With the input above, the output is still as expected without any extra characters in my case: 
![degrees](https://user-images.githubusercontent.com/12657033/85870227-15320600-b7cd-11ea-922b-bc97c43a848e.png)
Can you verify that we use the same software version? I execute Python from Ubuntu bash installed as [WSL 1 in Win10](https://docs.microsoft.com/en-us/windows/wsl/install-win10), just in case that might make a difference.
```
kvid@PC:~/src/formatc1702/WireViz/src$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
kvid@PC:~/src/formatc1702/WireViz/src$ python3.7 --version
Python 3.7.5
kvid@PC:~/src/formatc1702/WireViz/src$ git remote -v
origin  https://github.com/formatc1702/WireViz.git (fetch)
origin  https://github.com/formatc1702/WireViz.git (push)
kvid@PC:~/src/formatc1702/WireViz/src$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
kvid@PC:~/src/formatc1702/WireViz/src$ git log HEAD~1..HEAD
commit 66a47169e621d9605d783aabe65a0097e28609c2 (HEAD -> master, origin/master, origin/HEAD)
Merge: 6406e28 c1e6cf1
Author: Daniel Rojas <github@danielrojas.net>
Date:   Thu Jun 18 12:55:20 2020 +0200

    Merge branch 'dev'

commit c1e6cf14d2ea93f65d5c14ae8e3f30babcc4d8f9 (origin/dev)
Author: Daniel Rojas <github@danielrojas.net>
Date:   Thu Jun 18 12:55:04 2020 +0200

    Update readme
```
