### ISSUE TITLE
[feature] ability to import external yaml files for sharing connector and cable definitions

### ISSUE THREAD

**Issue by gmkado** [formatc1702/WireViz#220]
I would love to be able to have all my connector definitions in a single file and include it into my cable drawing yamls.  This would allow for things like a shared "library" of connectors that can be shared across a company.

From my searches online there are ways to do this with pyyaml:
- https://stackoverflow.com/questions/528281/how-can-i-include-a-yaml-file-inside-another
- https://gist.github.com/joshbode/569627ced3076931b02f
- https://pypi.org/project/pyyaml-include/

I tried adding [this code](https://gist.github.com/joshbode/569627ced3076931b02f) to the `wireviz.py` dev build but keep running into yaml syntax errors.  My knowledge of yaml parsing is pretty limited.

**Comment by kvid** [comment]
Thank you for your effort, but please try including your library using the existing [command line option](https://github.com/formatc1702/WireViz/tree/master/docs#command-line-options) `--prepend-file`.

**Comment by gmkado** [comment]
oops, should have read the docs better.  Thanks this does the trick!

**Comment by gmkado** [comment]
Hmm I'm going to re-open this because the `--prepend-file` leaves something to be desired.  Ideally you would be able to keep common connector and cable definitions in a separate folder and point to it.  But doing this breaks paths to image files referenced by the definitions.

**Comment by kvid** [comment]
> Hmm I'm going to re-open this because the `--prepend-file` leaves something to be desired. Ideally you would be able to keep common connector and cable definitions in a separate folder and point to it. But doing this breaks paths to image files referenced by the definitions.

The PR #189 already implements relative image paths differently, but your use case is still an issue and I describe the root cause in https://github.com/formatc1702/WireViz/pull/189#discussion_r593457127.

**Comment by formatc1702** [comment]
There has been some progress in #189 regarding this issue, @gmkado please have a look and feel free to post feedback.

**Comment by Liambeguin** [comment]
What about having something like this:
```yaml
templates:
  includes:
    - includes/DB9.yaml
    - includes/molex.yaml
    - include/inline_headers.yaml
```

This would make it explicit that this specific harness file depends on a list of "libraries"

Thanks for your work on this tool! It's really great at making harness drawings more efficient!

**Comment by kvid** [comment]
The YAML parser library we currently use seems to need the full YAML contents as one long string before beginning the parsing. That's  why it's a bit hard to use YAML for specifying more YAML files to include. I don't know if the suggested #223 might help?

**Comment by martinrieder** [comment]
@kvid take a look at https://github.com/adobe/himl and https://github.com/zerwes/hiyapyco

The hierarchical loading of YAML files could happen before the parsing in any other library, even the current one.

I still find the concept of using include statements quite promising. Since YAML uses # to start comments, you could theorerically employ any C code preprocessor with:

`#include "templates.yml"`

If it wasn't for the Windows compatibility, the beginning of a YAML file could even carry a shebang statement like:

`#!/usr/bin/wireviz --prepend-file xyz.yml`

This could turn your YAML file into an executable script!

**Comment by tobiasfalk** [comment]
@martinrieder what is the Problem with windows, is this something purely becaus of the YAML library or what?

**Comment by tobiasfalk** [comment]
One way could be to do it like/with a preprocessor, that goes through the file befor it is treated like a YAML file.

**Comment by martinrieder** [comment]
@tobiasfalk see here: https://realpython.com/python-shebang/

The Windows CMD processor does not recognize this statement, but there are workarounds. This method would also rely on STDIN/STDOUT, and which is WIP.

Having the possibility to store CLI arguments in the YAML file would be a great way to generate reproducible output. We should place this header before an eventual `---` block start, so it could be processed before any YAML code.

**Comment by tobiasfalk** [comment]
Then why not have the input file be a `.wz`(WireViz) file, this way one can add the association for Windows and the first line for Unix/Linux systems.
Then WiereViz takes this file let's a Preprocessor run over it, wich add all the includes and so, and exports a pure YAML file(`.wz.yalm`) wich then runs through the current code.

Similar to how a C compiler does it.

**Comment by martinrieder** [comment]
@tobiasfalk I suggested Jinja in #377 for the HTML output. It could be applied to the input YAML as well!

**Comment by tobiasfalk** [comment]
@martinrieder yes would also work, personally I would prefer C/C++ style, since I am familiar with it

**Comment by martinrieder** [comment]
What do you think about the YAML addition that [LamaAni/bole](https://github.com/LamaAni/bole) suggests:
```yaml
settings:
    inherit: False # If true, allow inherit parent folders.
    inherit_siblings: True # If true allow inherit configuration files in the same source directory.
    allow_imports: True # If false dose not allow imports.
    use_deep_merge: True # Merge configurations via deep merge. If false, Only root keys are merged (and overwritten)
    concatenate_lists: True # When merging, append the merged list to the current one.
imports:
    - "**/*.config.yaml" # Recursively import all .config.yaml
    - path: my-config.yaml
      required: False # this item is not required.
      recursive: null # Applies if glob. Import recursively.
environments:
    [env name]:{ config overrides (any)}
```

It comes really close to what was suggested earlier.
