### ISSUE TITLE
[Suggestion] Possible improvement on multi row connectors 

### ISSUE THREAD

**Issue by ulek** [formatc1702/WireViz#232]
Hey, 
I decided to try and capture something in my projects.
This particular thing has many twisted shielded pairs (I know that is being worked on)
The other thing that it utilizes multi row connectors (either 2 or 3). 
Very often on those type of connectors the signals are placed on multiple rows next to each other. I.e. in 16 pin 2 row connector very often pins 1 and 9 carry + and - of the same signal. 
Now if you just lay out the pins numerically it, it creates a mess as attached
![staggeredConnectorsEx](https://user-images.githubusercontent.com/7356948/115111753-cddd5780-9f4f-11eb-9444-ef98c2b0cb25.png)

Maybe there could some property of a connector that would group the pins either "logically" or "per row basis", 1 right next to 9, 2 right next to 10 etc. Placing pins in that order on the graph would allow to deal better with the resulting rats nest.
I'm not sure what would be the best way of dealing with bit. Maybe staggering/offsetting the second row pins with respect to the first row, be in line but have some different coloring.

**Comment by formatc1702** [comment]
Have you tried using the `pins` attribute of the connector? Here's a minimal example.

```yaml
X1:
  pins: [1,9,2,10]
  pinlabels: [sig1+, sig1-, sig2+, sig2-]
```

This way, you can force the pin order to whatever you need.

**Comment by ulek** [comment]
Actually just this morning noticed that example. So my bad on that end. 

However it still would be nice if we could somehow specify a connector property that would automatically for you.
like a maybe a multirow property that you would say how many rows, how pins set up etc.

I have untangled one of the connectors but the other one is a weird 3 row (8-7-8) no fighting with that one at the moment
Once I have that I'll do my best to update here

**Comment by kvid** [comment]
> However it still would be nice if we could somehow specify a connector property that would automatically for you.
> like a maybe a multirow property that you would say how many rows, how pins set up etc.

How about a new alternative to specify `pincount` as a list of pincounts in each pin group (for each row in your case)? In your case, it could look something like this:
```yaml
connectors:
  J1-M:
    type: Samtec
    subtype: female
    pincount: [8, 8]
    pinlabels: [sig1+,sig2+,sig3-,NC,SHIELD,NC,NC,sig4+,sig1-,sig2-,sig3+,NC,NC,NC,NC,sig4-]
  J2-I:
    type: Samtec
    subtype: female
    pincount: [8, 7, 8]
    pinlabels: [a,b,sig1+,sig2-,NC,d,e,f,g,h,sig3+,sig2+,NC,i,j,k,sig1-,sig3-,GND,NC,m,n,o]
```
I suggest rendering such pin groups like this:
![issue232-mod gv](https://user-images.githubusercontent.com/12657033/115171595-a4ddd380-a0c3-11eb-8fdf-870013b08cf2.png)
If combined with `pins` with custom pin names and/or ordering, the custom pins can also be split into groups similar to the default numeric pin names as shown above. Is this flexible enough, or do we also sometimes need to specify how to interleave the pin groups?
 - In the example above, the first pin from each group are strictly ordered by group index.
 - One alternative could be to order the first pin from large groups above the first pin from smaller groups, e.g. pin 16 above pin 9 for `J2-I` in your case.
 - Maybe even a custom group order might be needed sometimes?
