### ISSUE TITLE
inline connectors or cables into connections?

### ISSUE THREAD

**Issue by egradman** [formatc1702/WireViz#259]
It would be very helpful to be able to inline a connector or a cable into a connection!

```
connectors:
  X1:
    type: D-Sub
    subtype: female
    pinlabels: [DCD, RX, TX, DTR, GND, DSR, RTS, CTS, RI]
  X2:
    type: Molex KK 254
    subtype: female
    pinlabels: [GND, RX, TX]

connections:
  -
    - X1: [5,2,3]
    - W1:
         gauge: 0.25 mm2
         length: 0.2
         color_code: DIN
         wirecount: 3
         shield: true
    - X2: [1,3,2]
```

(this implies an ordering on the cable of `[1-3]`)
