### ISSUE TITLE
[feature] Add support for cable splicing

### ISSUE THREAD

**Issue by formatc1702** [formatc1702/WireViz#26]
Possibly using a "pseudo-connector" linking e.g. one wire from the left and two wires from the right.

Proof-of-concept:

```
connectors:
  X1:
    pincount: 5
  X2:
    pincount: 8
  S1:
    category: ferrule # TODO: splice
    pincount: 1
    type: Solderjoint + Tape
    notes: splice
  S2:
    category: ferrule # TODO: splice
    pincount: 1
    type: Solderjoint + Tape
    notes: splice

cables:
  W1: &template_wire
    category: bundle
    wirecount: 3
    gauge: 0.25
    length: 1
    show_name: false
    colors: [PK]
  W2:
    <<: *template_wire
    wirecount: 2
    length: 0.8
    colors: [TQ, YE]
  W3:
    <<: *template_wire
    wirecount: 5
    length: 0.2
    colors: [TQ, TQ, YE, YE, YE]

connections:
  -
    - X1: [1-3]
    - W1: [1-3]
    - X2: [1-3]
  -
    - X1: [4,5]
    - W2: [1,2]
  -
    - W2: 1
    - S1: 1
  -
    - W2: 2
    - S2: 1
  -
    - S1: [1,1]
    - W3: [1,2]
    - X2: [4,5]
  -
    - S2: [1,1,1]
    - W3: [3,4,5]
    - X2: [6,7,8]
```

![test](https://user-images.githubusercontent.com/2447251/85919501-d8691c00-b86b-11ea-8484-63335d198691.png)
