### ISSUE TITLE
Loops function

### ISSUE THREAD

**Issue by TTROD2MLE** [formatc1702/WireViz#260]
Hi all,
I'm trying to use the Loops function but I can't find any example.
What I want to do is to connect pins on a same connector and I guess this is the right function to use.
Can anybody help me?
Thanks!

**Comment by formatc1702** [comment]
Hi,

- The actual `loops` attribute of a connector is very primitive. It is a list, where every entry needs to be a list with exactly two pin numbers. You cannot control the apppearance (color) or any parameters of the loop "wire"
- You can also create a loop using a real `cable` inbetween, but the rendering admittedly leaves something to be desired.

See the following code which implements both variants:
```yaml
connectors:
  X1:
    pincount: 4
    loops:
      - [1, 2]  # simple loop

cables:
  W1:
    wirecount: 1
    colors: [GN]

connections:
  -  # loop using a "real" wire
    - X1: [3]
    - W1: [1]
    - X1: [4]
```

Result:
![loops](https://user-images.githubusercontent.com/2447251/143066807-cdc654a5-c662-41e9-8c2c-126c780a03fc.png)
