### ISSUE TITLE
[feature] pincolors specification for connector pins does not accept striped/banded combo code

### ISSUE THREAD

**Issue by Halfwalker** [formatc1702/WireViz#272]
Looks like specifying pincolors in a connector will not accept (silently ignores) combination color codes for striped/banded colors.
Using the following:
```
connectors:
  Elite-A36:
    type: Haltech 34
    pins:
      - A01
      - A02
      - A03
      - A04
      - A05
      - A25

  EA1:
    pins:
      - EA1-1
      - EA1-2
      - EA1-3
      - EA1-4
      - EA1-5
      - EA1-6
      - EA1-7
      - EA1-8
    pincolors: [BU, WHGN, BK, BKYE, IV, BKRD, WH, GY]

  EA2:
    pins:
      - EA2-1
      - EA2-2
      - EA2-3
      - EA2-4
      - EA2-5
    pincolors: [BK, BKRD, IV, WH, BKRD]

cables:
  EA1-Elite:
    category: bundle
    gauge: 20 AWG
    length: 0.2
    wirecount: 2
    colors: [GN, RD]


connections:
  -
    - Elite-A36: [A01, A25]
    - EA1-Elite: [1-2]
    - EA1: [EA1-2, EA1-8]
```
results in this
![image](https://user-images.githubusercontent.com/1365031/152694062-5c256028-b100-470a-b186-b77db72749cb.png)

Everything looks fine except the combo colors for pins are missing.  Given that it's just a small square of color, this is likely just the way it is.  Any chance of expanding the color square to a small rectangle to incorporate striped wires ?  For example, **RDYE** could produce 
![image](https://user-images.githubusercontent.com/1365031/152694195-f8e1da3c-1207-4447-9d7f-90e44659cb4c.png)
This would be extremely helpful when building a harness to connect into existing connectors.  You tag the existing connectors with the wire colors they have, and that provides a visual check when building the harness.
