### ISSUE TITLE
[feature] Accept alternative input syntax for connector pins

### ISSUE THREAD

**Issue by kvid** [formatc1702/WireViz#279]
@Halfwalker wrote:
> 
> Perhaps a syntax change/option would help for this. Right now connectors define pins as a list, which is order-dependent. 3rd one defined is pin 3 etc. Pinlabels are defined the same way - see the connectors above. This means making sure that the pin labels are in the correct order to match the pin colors ...
> 
> How about defining pins individually ?
> 
> ```yaml
>   A4:
>     pins:
>       - pin: 1
>         label: AC lock sensor
>         color: GNYE
>       - pin: 2
>         label: AC lock sensor
>         color: VTWH
>       - pin: 3
>         label: NC
>       - pin: 4
>         label: AC magnetic clutch
>         color: BU
> ```

That is a good idea. It should be possible to accept an input syntax similar to your suggestion as an alternative to the existing syntax, and WireViz can easily map the values from such an input into the current data structure. This way, users can select the easiest syntax for each connector and cable. Implementing such a feature should be quite easy and only involve `__post_init__()` of the classes `Connector` and `Cable`, but I suggest raising a separate feature request issue for it, as it is independent from the automatic ordering in #275.

Edit: To support such a feature also for cables/bundles, then I guess we need a new attribute `wires` that can take a list of `dicts`.  Such a syntax alternative might also be an advantage when new attributes per wire is requested, like in #56 or #268. However, supporting custom wire naming/renumbering as is already supported for connector pins, would require numerous changes in several source files, and should therefore perhaps be out of scope for now.

_Originally posted by @kvid in https://github.com/formatc1702/WireViz/issues/275#issuecomment-1039626280_

**Comment by mofosyne** [comment]
This issue ticket is more than a few years old, so looks like it will take a while. In the meantime, I really like the syntax from an maintainability and ergonomics perspective that I would like to use it more to see if it works out practically.

To this end, decided to generate a helper python preprocessor script (using claude) specifically for this proposal to test it out. Sharing it here in case others want to see if it works in practice. As this will help with writing non contiguous pinouts. Especially for very large pinouts where most of the pinouts is not used.

**Plus I can see if this form gets standardised well enough... we could likely create a database of connectors as well**

**Two extra divergence from the above proposed syntax is to add a 'fullname' entry which fills in the 'note' section with a legend list. Future implementation may want to bake it into the actual pinout as a smaller font under the pin name. Also added multi-pin entries as we can have multiple pins that both share the same label and meaning**

Download: [wireviz_issue_279_preprocessor.py](https://github.com/user-attachments/files/29272723/wireviz_issue_279_preprocessor.py)

```python
#!/usr/bin/env python3
"""
wireviz_pre.py — WireViz preprocessor

Converts the proposed map-style pin syntax (from issue #279) to the
parallel-list syntax that WireViz currently expects, writes the result
to ./build/<filename>.yml, then invokes wireviz on it automatically.

NOTE: This script exists solely as a workaround for a missing WireViz feature.
If the following issue is ever implemented and closed, this preprocessor
becomes redundant and can be dropped in favour of native WireViz support:

  https://github.com/wireviz/WireViz/issues/279
  "[feature] Accept alternative input syntax for connector pins"

Extended syntax supported beyond issue #279:

  1. Multi-pin entries — one logical signal spanning multiple pins:

       - pin: [20, 21]
         label: DICOM
         fullname: Digital I/F power supply input

     Expands to one row per pin, all sharing the same label/color.

  2. Full name annotation — a human-readable description per signal:

       - pin: 15
         label: SON
         fullname: Servo-on

     fullname values are collected and appended to the connector's notes
     field as a reference table, since WireViz has no per-pin description
     field. Example output in notes:

       SON  : Servo-on
       RES  : Reset
       DICOM: Digital I/F power supply input

Usage:
  python wireviz_pre.py <input.yml> [<input2.yml> ...]

Output files are written to ./build/ preserving the original filename,
and wireviz is run on each one automatically.
"""

import sys
import os
import copy
import subprocess
import yaml


def is_map_style_pins(pins_value) -> bool:
    """Return True if pins is a list of dicts with a 'pin' key."""
    return (
        isinstance(pins_value, list)
        and len(pins_value) > 0
        and isinstance(pins_value[0], dict)
        and "pin" in pins_value[0]
    )


def expand_map_pins(pins_list: list) -> tuple[dict, str]:
    """
    Convert a list of pin dicts into parallel lists, handling multi-pin
    entries and collecting fullname annotations.

    Returns (expanded_dict, notes_string).
    notes_string is empty if no fullnames were defined.
    """
    pins = []
    pinlabels = []
    pincolors = []
    has_labels = False
    has_colors = False

    # label -> fullname, insertion-ordered, deduped (multi-pin entries
    # share one fullname row)
    fullnames: dict[str, str] = {}

    for entry in pins_list:
        pin_val = entry["pin"]
        # Normalise to a list so multi-pin and single-pin share one path
        pin_ids = pin_val if isinstance(pin_val, list) else [pin_val]

        label = str(entry.get("label", ""))
        color = entry.get("color", "")
        fullname = entry.get("fullname", "")

        for pid in pin_ids:
            pins.append(pid)
            pinlabels.append(label)
            pincolors.append(color)

        if label:
            has_labels = True
        if color:
            has_colors = True
        if fullname and label:
            fullnames[label] = fullname

    result = {"pins": pins}
    if has_labels:
        result["pinlabels"] = pinlabels
    if has_colors:
        result["pincolors"] = pincolors

    # Build notes table if any fullnames were given
    notes = ""
    if fullnames:
        width = max(len(k) for k in fullnames)
        lines = [f"{k:<{width}}: {v}" for k, v in fullnames.items()]
        notes = "\n".join(lines)

    return result, notes


def preprocess(data: dict) -> dict:
    """
    Walk the parsed YAML dict and expand any map-style pin definitions
    found under connectors.
    """
    data = copy.deepcopy(data)

    connectors = data.get("connectors", {})
    for name, connector in connectors.items():
        if not isinstance(connector, dict):
            continue
        pins_value = connector.get("pins")
        if pins_value is None:
            continue
        if not is_map_style_pins(pins_value):
            continue

        expanded, notes = expand_map_pins(pins_value)
        del connector["pins"]

        new_connector = {}
        for k, v in connector.items():
            if k in ("pinlabels", "pincolors"):
                print(
                    f"  WARNING: connector '{name}' had both map-style pins and "
                    f"a top-level '{k}' — the map-style definition wins."
                )
                continue
            new_connector[k] = v
        new_connector.update(expanded)

        # Append generated fullname table to any existing notes
        if notes:
            existing = new_connector.get("notes", "")
            new_connector["notes"] = (existing + "\n\n" + notes).strip()

        connectors[name] = new_connector

        pin_ids = expanded["pins"]
        print(f"  Expanded connector '{name}': {len(pin_ids)} pins -> {pin_ids}")

    data["connectors"] = connectors
    return data


def process_file(input_path: str, build_dir: str) -> str:
    """Read, preprocess, and write to build_dir. Returns output path."""
    with open(input_path, "r") as f:
        raw = yaml.safe_load(f)

    if not isinstance(raw, dict):
        raise ValueError(f"Expected a YAML mapping at the top level of {input_path}")

    print(f"Processing: {input_path}")
    processed = preprocess(raw)

    os.makedirs(build_dir, exist_ok=True)
    basename = os.path.basename(input_path)
    output_path = os.path.join(build_dir, basename)

    with open(output_path, "w") as f:
        yaml.dump(processed, f, default_flow_style=False, allow_unicode=True, sort_keys=False)

    print(f"  Written:  {output_path}")
    return output_path


def run_wireviz(output_paths: list):
    """Invoke wireviz on each preprocessed file."""
    for path in output_paths:
        print(f"Running: wireviz {path}")
        result = subprocess.run(["wireviz", path])
        if result.returncode != 0:
            print(f"  ERROR: wireviz exited with code {result.returncode}", file=sys.stderr)
            sys.exit(result.returncode)


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)

    build_dir = "./build"
    output_paths = []

    for input_path in sys.argv[1:]:
        if not os.path.isfile(input_path):
            print(f"ERROR: File not found: {input_path}", file=sys.stderr)
            sys.exit(1)
        out = process_file(input_path, build_dir)
        output_paths.append(out)

    print()
    run_wireviz(output_paths)


if __name__ == "__main__":
    main()
```

``` yaml
# test_harness.yml
# Uses the extended map-style pin syntax from WireViz issue #279.
# Run through wireviz_pre.py before passing to wireviz.
#
# Scenario: wiring from a controller (X1, X2, X3) to a
# Mitsubishi MR-J4 servo drive CN1 I/O connector (X4).
#
#   - X1 (Generic 10-pin) : controller digital outputs -> servo inputs
#   - X2 (Generic 4-pin)  : controller digital inputs <- servo outputs
#   - X3 (Generic 2-pin)  : 24V I/O power supply
#   - X4 (CN1 50-pin)     : Mitsubishi MR-J4 servo drive I/O connector

connectors:
  X1:
    type: Generic
    subtype: female
    notes: Controller digital outputs
    pinlabels: [SON, RES, CR, EM2, LSP, LSN]

  X2:
    type: Generic
    subtype: female
    notes: Controller digital inputs
    pinlabels: [ZSP, INP, ALM, RD]

  X3:
    type: Generic
    subtype: female
    notes: 24V I/O power supply
    pinlabels: [24V, GND]

  X4:
    # Mitsubishi MR-J4 servo drive CN1 I/O connector (50-pin).
    # Only connected pins are listed — the map syntax makes absent
    # pins self-evident without counting positions in a parallel list.
    # Multi-pin entries (e.g. pin: [20, 21]) share one signal name.
    # fullname values are collected into the connector notes as a reference table.
    type: 50-pin MIL connector
    subtype: female
    notes: "Mitsubishi MR-J4 CN1 I/O"
    pins:
      - pin: 15
        label: SON
        fullname: Servo-on
      - pin: 19
        label: RES
        fullname: Reset
      - pin: 41
        label: CR
        fullname: Clear
      - pin: 42
        label: EM2
        fullname: Forced stop 2
      - pin: 43
        label: LSP
        fullname: Forward rotation stroke end
      - pin: 44
        label: LSN
        fullname: Reverse rotation stroke end
      - pin: 23
        label: ZSP
        fullname: Zero speed detection
      - pin: 24
        label: INP
        fullname: In-position
      - pin: 48
        label: ALM
        fullname: Malfunction
      - pin: 49
        label: RD
        fullname: Ready
      - pin: [20, 21]
        label: DICOM
        fullname: Digital I/F power supply input
      - pin: [46, 47]
        label: DOCOM
        fullname: Digital I/F common

cables:
  W1:
    notes: Digital outputs — controller to servo
    gauge: 0.25 mm2
    length: 0.5
    wirecount: 6
    colors: [WH, YE, GN, RD, BU, VT]

  W2:
    notes: Digital inputs — servo to controller
    gauge: 0.25 mm2
    length: 0.5
    wirecount: 4
    colors: [WH, YE, GN, RD]

  W3:
    notes: 24V I/O power
    gauge: 0.5 mm2
    length: 0.5
    wirecount: 2
    colors: [RD, BK]

connections:
  # Digital outputs: controller X1 -> servo X4 inputs
  - - X1: [1, 2, 3, 4, 5, 6]
    - W1: [1, 2, 3, 4, 5, 6]
    - X4: [15, 19, 41, 42, 43, 44]

  # Digital inputs: servo X4 outputs -> controller X2
  - - X4: [23, 24, 48, 49]
    - W2: [1, 2, 3, 4]
    - X2: [1, 2, 3, 4]

  # 24V I/O power -> DICOM (pin 20 only; 21 is a parallel internal connection)
  - - X3: [1, 2]
    - W3: [1, 2]
    - X4: [20, 46]
```

<img width="2092" height="843" alt="Image" src="https://github.com/user-attachments/assets/4a94650f-7a70-412d-83bb-3f38dcae092d" />
