### ISSUE TITLE
[feature] shield: true for connectors

### ISSUE THREAD

**Issue by RobEnduro** [formatc1702/WireViz#285]
At this time, it doesn't seem like its possible to define a shield for connectors, only for cables.
Take Demo 01 for an example, where X1 is a 9-pin D-sub. It has pin 5 connected to the cable shield.
Generally, D-Sub connectors have a metal housing which could of course form electrical connection.
Outside of defining a "9-pin" connector with an explicit 10th pin for this purpose, is this something that can be done, or a possible feature that could be added?

**Comment by kvid** [comment]
Thank you for your suggestion. What would you expect the connector should look like in the output diagram if implementing such a feature? Should it just be added as pin with a special name, or is that not enough?

Currently, there is no shield specifier for connectors, but you can specify custom pin names, e.g. like this if you want a pin named `s`:
```yaml
connectors:
  X1:
    type: D-Sub
    subtype: female
    pinlabels: [DCD, RX, TX, DTR, GND, DSR, RTS, CTS, RI, SHIELD]
    pins: [1, 2, 3, 4, 5, 6, 7, 8, 9, s]
```
Does this create the diagram you want, or would you like something different?

![issue285c](https://user-images.githubusercontent.com/12657033/179018916-56c9a060-af25-4b8b-a3c9-0c00cf8e70eb.png)
