### ISSUE TITLE
[feature] connector pin attributes

### ISSUE THREAD

**Issue by T0jan** [formatc1702/WireViz#291]
Hello,

I usually use additional parameters in my harness plans like the signal direction or the voltage levels as additional layers of security. One could add them to the pinlabels ofc but I would like to see them in an additional column for each connector. If it is not already implemented and I missed it somewhere I would suggest a solution with optional attributes for the pinout definition:

```
connectors:
  J101:
    pinlabels: [+5V, +5V, GND, GND, RX+, RX-, TX+, TX-, SDA, SCL]
    pinattributes1: [PWR, PWR, PWR-RET, PWR-RET, IN, IN, OUT, OUT, IO, OUT]
    pinattributes2: [5V, 5V, GND, GND, RS422, RS422, RS422, RS422, 3V3, 3V3]
```

I think giving the option to add two or three individual attribute fields should cover the most cases in which this could be useful.

**Comment by kvid** [comment]
Thank you @T0jan for this feature suggestion. I'm sorry you had to wait so long without any feed-back. I'm not against your suggestion, but I just want to present a possible/optional alternative syntax to specify the same attributes:
```yaml
connectors:
  J101:
    pinlabels:
      - [+5V, PWR,     5V]
      - [+5V, PWR,     5V]
      - [GND, PWR-RET, GND]
      - [GND, PWR-RET, GND]
      - [RX+, IN,      RS422]
      - [RX-, IN,      RS422]
      - [TX+, OUT,     RS422]
      - [TX-, OUT,     RS422]
      - [SDA, IO,      3V3]
      - [SCL, OUT,     3V3]
```
