### ISSUE TITLE
[feauture] ignore additional components in bom

### ISSUE THREAD

**Issue by ask6483** [formatc1702/WireViz#300]
Is it possible to also ignore additional components in bom generation?
For example **ignore_in_bom** will hide connector housing but not crimp terminals:
```
  J1:
    pincount: 2
    type: PicoBlade 1.25 mm 
    subtype: Receptacle Crimp Housing
    manufacturer: Molex
    mpn: '510210200'
    pinlabels: [GND, VCC]
    notes: Camber Main PCB
    ignore_in_bom: true
    additional_components:
      -
        type: Female Crimp Terminal
        subtype: |
          PicoBlade 1.25 mm 
          Tin Plating, 26-28AWG
        qty_multiplier: populated
        manufacturer: Molex
        mpn: '500798001'
```
I want to create cable diagram but the part is available as pre-crimped wire so there is only one item in bom.
