### ISSUE TITLE
Multiple suppliers per connector/cable?

### ISSUE THREAD

**Issue by nyq** [formatc1702/WireViz#302]
Is there a way to specify multiple suppliers for the same connector/cable? I tried so specify more than one pair of supplier/spn keys, but all it does is simply overrides all previous pair values and just uses the last pair specified.

This feature is often needed in production environments, as it is typical to maintain several suppliers for the same part on file to ensure the ability to purchase from alternative sources if there are stocking issues with the primary supplier.

**Comment by kvid** [comment]
Thank you for your use case description. Currently, it's not possible to specify more than one mpn or more than one spn for any component. To enable something like that, it must be defined a clear and unambiguous way to display a component with many such values in a diagram, and in the BOM. Please suggest.

Your suggested input syntax is not valig YAML, as all keys in a mapping must be unique. However, maybe a variation like this, might be possible:
```yaml
connectors:
  X1:
    manufacturer:
      Lolex:
        mpn: 12345
        spn:
          MousiKey: MK-12345
          ArroArk: AA-12345
      ET Connection:
        mpn: 54321
        spn:
            MousiKey: MK-54321
            ArroArk: AA-54321
```
