### ISSUE TITLE
Tolerance in cable lengths

### ISSUE THREAD

**Issue by ct2irw** [formatc1702/WireViz#306]
Hi there,

My name is Diogo. So often manufacturers ask to include tolerances in the cable lengths. I think it would make sense to have a key/value for that. The way I've implemented that was by mostly cloning the length key... The only change I did in that was to inherit the units from the length if none is provided instead of assuming 'm' like length does. Ideally, it would process different tolerances like -10mm and +15mm, but I did not have time to mess with that.

Let me know if you want any help implementing that.

Best regards,
DIogo

**Comment by formatc1702** [comment]
It would be nice if this didn't require an additional key/value in the YAML, but if it could be parsed within the `length` attribute itself. Internally, it probably makes sense to have it as a separate variable for sure.

Some suggestions for YAML input:
```yaml
length: 100  # assume default unit
length: 200 mm  # explicit unit
length: 300 ±5 mm   # place unit before or after tolerance? allow both?
length: 400 +-5 mm  # allow +- instead of ± for easier input
length: 500 +5 -0  # allow asymmetric tolerance
length: 600 ±10%  # allow percentages?
                  # show as percentage in output or do the math?
                  # maybe as a second step later on
length: 700~750  # allow length range?
```
