### ISSUE TITLE
Can't get Daisy chaining working. Help.

### ISSUE THREAD

**Issue by Tensdale** [formatc1702/WireViz#313]
I need to have this fit a normal sized paper, thought I could move Cable 2 and the RGB_led connector down with Daisy chaining bit cant get it working. Can anyone help?

![dsub9_connector](https://user-images.githubusercontent.com/128591673/229192661-3d4c2843-a879-4d1d-ae61-2251a481a233.png)

The connections in the code:

connections:
  - [dsub9: 1, C1: 1, fixture: Reset]
  - [dsub9: 2, C1: 2, led_driver: "VCC"]
  - [dsub9: 3, C1: 3, fixture: "3V3"]
  - [dsub9: 4, C1: 4, led_driver: "Red"]
  - [dsub9: 5, C1: 5, switch: "1"]
  - [dsub9: 6, C1: 6, led_driver: "Blue"]
  - [dsub9: 7, C1: 7, led_driver: "Green"]
  - [dsub9: 8, C1: 8, fixture: SWD_IO]
  - [dsub9: 9, C1: 9, fixture: SWD_CLK]
  - [dsub9: 10, C1: 10, fixture: GND]
  - [led_driver: "Red", C2: 1, rgb_led: R]
  - [led_driver: "Blue", C2: 2, rgb_led: G]
  - [led_driver: "Green", C2: 3, rgb_led: B]
  - [C1: 10, rgb_led: GND]
  - [C1: 10, switch: GND]
'''

I tried daisy chaining like shown below but it didn't change anything. Should I move the connectors down some other way?

connections:
  -
    - dsub9: 1
    - C1: 1
    - fixture: Reset
  -
    - dsub9: 2
    - C1: 2
    - led_driver: "VCC"
  -
    - dsub9: 3
    - C1: 3
    - fixture: "3V3"
  -
    - dsub9: 4
    - C1: 4
    - led_driver: "Red"
  -
    - dsub9: 5
    - C1: 5
    - switch: "1"
  -
    - dsub9: 6
    - C1: 6
    - led_driver: "Blue"
  -
    - dsub9: 7
    - C1: 7
    - led_driver: "Green"
  -
    - dsub9: 8
    - C1: 8
    - fixture: SWD_IO
  -
    - dsub9: 9
    - C1: 9
    - fixture: SWD_CLK
  -
    - dsub9: 10
    - C1: 10
    - fixture: GND
  -
    - led_driver: [Red, Blue, Green]
    - C2: [1, 2, 3]
    - rgb_led: [R, G, B]
  -
    - C1: 10
    - rgb_led: GND
  -
    - C1: 10
    - switch: GND
'''

**Comment by kvid** [comment]
- Thank you for sharing your usecase. It seems to be related to #293 and possibly also #209. The order of the elements in each connection specify wires to be drawn from left to right in the diagram.
- You seems to have terminated the `C1:10` wire at 3 different connectors which is normally hard to do in real life. I assume you either intend to connect these `GND` terminals together with short wires to a common junction point (using a ferrule or soldering), or daisy chaining short wires between the same terminals. I suggest you specify in the diagram one of these ways. See my alternatives below.
- Is it your intention to connect `G` to `Blue` and `B` to `Green` at the `rgb_led` connector? Their names seems to have been swapped.
- First, I show how a ferrule can be used to avoid terminating the same wire at several connectors:
![issue313-b](https://user-images.githubusercontent.com/12657033/229239613-57899a57-e1f8-4ce7-91b2-5e57dc7620a1.png)
<details>
<summary><b>Expand to show YAML code for the diagram above</b></summary>

```yaml
connectors:
  dsub9:
    type: SUBD-9
    subtype: female
    pinlabels: [Reset, VCC_RGB, VCC_Programming, RGB_Red, Switch, RGB_Blue, RGB_Green, SW_DIO, SW_CLK, Housing (GND)]
  fixture:
    type: custom
    pinlabels: [Reset, "3V3", SWD_IO, SWD_CLK, GND]
  led_driver:
    type: custom
    pinlabels: ["VCC", "Red", "Blue", "Green"]
  rgb_led:
    type: custom
    pinlabels: [R, G, B, GND]
  switch:
    type: custom
    pinlabels: ["1", GND]
  ferrule:
    style: simple
    pincount: 1
cables:
  C1:
    gauge: 0.22 mm2
    length: 1 m
    colors: [BK, BN, WH, RD, VT, BU, GN, OG, GY, YE]
  C2:
    colors: [RD, BU, GN]
  C3:
    category: bundle
    colors: [YE,YE,YE]
    gauge: 0.22 mm2
    length: 0.1 m
    show_name: False
connections:
  -
    - dsub9: [1-10]
    - C1: [1-10]
  -
    - C1: [1,3,8-10]
    - fixture: [1-5]
  -
    - C1: [2,4,6-7]
    - led_driver: [1-4]
  -
    - led_driver: [2-4]
    - C2: [1-3]
    - rgb_led: [1-3]
  -
    - C1: 5
    - switch: 1
  -
    - ferrule: 1
    - C3: 1
    - fixture: GND
  -
    - ferrule: 1
    - C3: 2
    - switch: GND
  -
    - ferrule: 1
    - C3: 3
    - rgb_led: GND
```
</details>

- Then I show how to daisy chain for a more compact diagram:
![issue313-c](https://user-images.githubusercontent.com/12657033/229240982-d52f9bb7-1037-40d9-a1a2-06d0219dd29a.png)
<details>
<summary><b>Expand to show YAML code for the diagram above</b></summary>

```yaml
connectors:
  dsub9:
    type: SUBD-9
    subtype: female
    pinlabels: [Reset, VCC_RGB, VCC_Programming, RGB_Red, Switch, RGB_Blue, RGB_Green, SW_DIO, SW_CLK, Housing (GND)]
  fixture:
    type: custom
    pinlabels: [Reset, "3V3", SWD_IO, SWD_CLK, GND]
  led_driver:
    type: custom
    pinlabels: ["VCC", "Red", "Blue", "Green"]
  rgb_led:
    type: custom
    pinlabels: [R, G, B, GND]
  switch:
    type: custom
    pinlabels: ["1", GND]
cables:
  C1:
    gauge: 0.22 mm2
    length: 1 m
    colors: [BK, BN, WH, RD, VT, BU, GN, OG, GY, YE]
  C2:
    colors: [RD, BU, GN]
  C3:
    category: bundle
    colors: [YE,YE]
    gauge: 0.22 mm2
    length: 0.2 m
    show_name: False
connections:
  -
    - dsub9: [1-10]
    - C1: [1-10]
  -
    - C1: [1,3,8-10]
    - fixture: [1-5]
  -
    - C1: [2,4,6-7]
    - led_driver: [1-4]
  -
    - rgb_led: [1-3]
    - C2: [1-3]
    - led_driver: [2-4]
  -
    - C1: 5
    - switch: 1
  -
    - rgb_led: GND
    - C3: 1
    - fixture: GND
  -
    - rgb_led: GND
    - C3: 2
    - switch: GND
tweak:
  override:
    graph:
      ranksep: "4"  # Increase horizontal spacing (default 2) for readability
```
</details>

- With default horizontal spacing, the wires drawn between `C1` and `led_driver` became hard to separate in this last diagram, so I doubled the horizontal spacing for readability.
