### ISSUE TITLE
[bug] incorrect designators for different coloured wires in bundles

### ISSUE THREAD

**Issue by Tyler-Ward** [formatc1702/WireViz#33]
When producing a bom containing several bundles of wires with different colours the designators are added to all wires for that gauge rather than just the ones that colour appears in. Below is a simple example based on ex02.yml. Will likely look at fixing this later today but recording it here in the meantime.

```
connectors:
  X1: &boo
    type: Molex Micro-Fit
    subtype: male
    pinout: [GND, VCC]
  X2: &con_power_f # define template
    type: Molex Micro-Fit
    subtype: female
    pinout: [GND, VCC]
  X3:
    <<: *con_power_f # create from template
  X4:
    <<: *con_power_f # create from template

cables:
  W1: &wire_power # define template
    category: bundle
    colors: [BK, RD] # number of wires implicit in color list
    gauge: 0.25 # assume mm2 if no gauge unit is specified
    show_equiv: true
    length: 0.2
  W2:
    <<: *wire_power # create from template
    colors: [BU, WH] # number of wires implicit in color list
  W3:
    <<: *wire_power # create from template

connections:
  -
    - X1: [1-2]
    - W1: [1-2]
    - X2: [1-2]
  -
    - X1: [1-2]
    - W2: [1-2]
    - X3: [1-2]
  -
    - X1: [1-2]
    - W3: [1-2]
    - X4: [1-2]
```

![image](https://user-images.githubusercontent.com/3390465/85946468-75938580-b93c-11ea-979c-c80530999af9.png)
