### ISSUE TITLE
Port unrecognized when specifying connections using pinout

### ISSUE THREAD

**Issue by Marsfan** [formatc1702/WireViz#38]
### Summary
I am trying to set up connections using the pin names specified in pinouts like in #10. It appears to be working properly, however, when I build the diagram, I get the warning. 

`Warning: node x1, port pGNDr unrecognized`

I am not sure what is happening, could you clear this up for me?

#### YAML File

```
connectors:
  X2:
    pinnumbers: [1,2]
    pinout: [GND, VCC]
  X1:
    pinnumbers: [1, 2, 3, 4]
    pinout: [GND, VCC, D+, D-]

cables:
  W1:
    wirecount: 2
    color_code: IEC

connections:
  -
    - X1: [GND, VCC]
    - W1: [1-2]
    - X2: [1-2]
```

#### Command Line Input/Output
```
$> wireviz test.yml
Warning: node X1, port pGNDr unrecognized
Warning: node X1, port pVCCr unrecognized
Warning: node X1, port pGNDr unrecognized
Warning: node X1, port pVCCr unrecognized
$>
```

#### Output from running on provided YAML file
![Output Image](https://user-images.githubusercontent.com/9311953/85960117-a8eb0a00-b966-11ea-894d-b6e5610280dc.png)
