### ISSUE TITLE
Ability to change numbering system on connectors

### ISSUE THREAD

**Issue by cocide** [formatc1702/WireViz#4]
I'm adding some 3 pin phones connectors to my layout and tracking the pins numerically (as 1, 2, 3) is not very useful since the connector is a tip, ring, sleeve type. I know I could add T, R, S into the pinout section, but I also need to track the names of what they are used for (in this case it is Dot, Dash, and Ground).

End results being: [KX3 Harness.pdf](https://github.com/formatc1702/WireViz/files/4826341/KX3.Harness.pdf)

```yml
connectors:
  Key:
    type: Phone Connector
    subtype: male 3.5
    pins: [T, R, S]
    pinout: [Dot, Dash, Ground]

cables:
  W1:
    gauge: 24 AWG
    length: 0.2
    color_code: DIN
    wirecount: 3
    shield: true

connections:
  -
    - Key: [S,R,T]
    - W1: [1,2,3]
  -
    - Key: S
    - W1: s
```
