### ISSUE TITLE
Image Types

### ISSUE THREAD

**Issue by kvid** [formatc1702/WireViz#445]
I noticed that the SVG image for a connector is not shown in the PNG output. I wonder if this is also observed by others. JPG, PNG, and GIF images in connectors seems to work fine, but a TIF image was rejected by Graphviz. It would be nice to create a test use case with all image types expected to work, and perhaps a separate (sub-)issue for unexpected outputs for such a test use case.

_Originally posted by @kvid in https://github.com/wireviz/WireViz/issues/443#issuecomment-2645515636_

Preliminary test use case YAML input:
```yaml
connectors:
  png: &png
    pincount: 4
    image:
      src: resources/MolexKK254_4-pin.png
  jpg:
    <<: *png
    image:
      src: resources/MolexKK254_4-pin.jpg
  svg:
    <<: *png
    image:
      src: resources/MolexKK254_4-pin.svg
  gif:
    <<: *png
    image:
      src: resources/MolexKK254_4-pin.gif
#  tif:
#    <<: *png
#    image:
#      src: resources/MolexKK254_4-pin.tif
#  webp:
#    <<: *png
#    image:
#      src: resources/MolexKK254_4-pin.webp
cables:
  w:
    category: bundle
    colors: [YE]
    length: 1
connections:
  - - png: [1]
    - w.: [1]
    - jpg: [1]
    - w.: [1]
    - svg: [1]
    - w.: [1]
    - gif: [1]
#    - w.: [1]
#    - tif: [1]
#    - w.: [1]
#    - webp: [1]
```
Image files expected to be in a `resources` subfolder:
![Image](https://github.com/user-attachments/assets/fedfd2c3-7dc4-431e-a608-6b46dac6f3ff) `MolexKK254_4-pin.png`
![Image](https://github.com/user-attachments/assets/4abf397f-868d-4b82-bac3-4501560829bf) `MolexKK254_4-pin.jpg`
![Image](https://github.com/user-attachments/assets/fad4acec-d8df-47ad-9c4f-fab9f83ac178) `MolexKK254_4-pin.svg`
![Image](https://github.com/user-attachments/assets/8f2e0bb1-c030-4da6-bcbd-ee839253fe19) `MolexKK254_4-pin.gif`

Please suggest including other image types you are able to use or any kind of improvements.
