### ISSUE TITLE
Overlapping simple connectors

### ISSUE THREAD

**Issue by JulienDevillers** [formatc1702/WireViz#450]
Hello,

Based on this configuration:
```
connectors:
  OpenWire:
    style: simple
    type: open wire
    ignore_in_bom: True
  
  Rescue: 
    pinlabels: [SIGNAL, GND]


cables:
  W2:
    wirecount: 2
    length: 1
    colors: [BK, GN]
    

connections:
  -
    - Rescue: [1-2]
    - <--
    - OpenWire.
    - W2: [1, 2]

```

I get this result:

![Image](https://github.com/user-attachments/assets/2e46ddb0-fb89-490d-868c-4a1eb23dc852)

It's nice but I need to cross the wires between W2 and rescue in order to have pin 1 of W2 go to pin 2 of Rescue and vice-versa. So I changed the connection to:
```
connections:
  -
    - Rescue: [1-2]
    - <--
    - OpenWire.[2,1]    # Here is the change
    - W2: [1, 2]

```

The result seems to be ok on a logical point of view but both open wires are now overlapping:

![Image](https://github.com/user-attachments/assets/a74ad8af-0351-4eb1-a985-fea72e04583b)

How should I do?

Thanks.
Julien
