### ISSUE TITLE
hide wiring information using workaround

### ISSUE THREAD

**Issue by snelweg** [formatc1702/WireViz#453]
When I do the hide wiring information as described in #212 then everything displays as it should except for when I use the length and gauge parameters for a cable.

The tweak as described in #212:

```
cables:
  230v:
    wirelabels: [fase,nul, aarde]
    colors: [BN,BU, GNYE]
    show_name: false
    show_wirecount: false     
    show_wirenumbers: false

connections:
  -
    - 230v

tweak:
  override:
    graph:
      ranksep: "0.5"  # Reduce the horizontal spacing (default 2)
    wireTweak: &wireTweak230
      shape: none  # Hide the surrounding frame
      fontsize: "12"  # Reduce the space needed for text
      fontcolor: white  # Same as background to hide the text

    230v:  
      <<: *wireTweak230
```
result:
![Image](https://github.com/user-attachments/assets/2d9d56ed-2b1e-4bd6-a454-7ef9b346d365)
(no display of the wiring information)

cable (230v) with a gauge and a length
```

cables:
  230v:
    length: 0.7
    gauge: 1.5
    wirelabels: [fase,nul, aarde]
    colors: [BN,BU, GNYE]
    show_name: false
    show_wirecount: false     
    show_wirenumbers: false

connections:
  -
    - 230v

tweak:
  override:
    graph:
      ranksep: "0.5"  # Reduce the horizontal spacing (default 2)
    wireTweak: &wireTweak230
      shape: none  # Hide the surrounding frame
      fontsize: "12"  # Reduce the space needed for text
      fontcolor: white  # Same as background to hide the text

    230v:  
      <<: *wireTweak230
```
Result:
![Image](https://github.com/user-attachments/assets/7cb2d00f-f2d0-4b41-b112-d3a25a3a926b)
(it displays the box on the result.)
