### ISSUE TITLE
[Feature Request] Multiple types of contacts in the same connector

### ISSUE THREAD

**Issue by blessedbiped** [formatc1702/WireViz#456]
There are a few connectors I use regularly (round milspec and TE HDP series come to mind, among others)  which require specific size contacts in particular locations. Is there an existing way to define this kind of setup? Something like 

- position : contact
    - [1-3] : 0460-202-16141 
    - 4 : 0460-202-12141
    - etc

![Image](https://github.com/user-attachments/assets/7f8f2210-0335-44a1-bec3-c4a37b9f3cd7)

**Comment by blessedbiped** [comment]
Duplicate of #372

**Comment by blessedbiped** [comment]
There is already a feature to define multiple part numbers in a bundle in the cable section, we could leverage the same syntax if it's simpler.

``` yaml
additional components:
    - 
        type: socket
        mpn: [socket a, socket a, socket b, socket a, socket c]

```
