### ISSUE TITLE
Loop color?

### ISSUE THREAD

**Issue by blackbit42** [formatc1702/WireViz#457]
```yaml
connectors:
  X1:
    pincount: 2
    pins: [1, 2]
  X2:
    pincount: 2
    pins: [1, 2]
    loops: [[1, 2]]

cables:
  W1:
    wirecount: 2
    colors: [GN, BN]

connections:
  -
    - X1: [1, 2]
    - W1: [1, 2]
    - X2: [1, 2]
```

![Image](https://github.com/user-attachments/assets/40dacc17-fcca-4ec6-aac6-28299e7e2450)

In this trivial example, how would I assign a color to the loop?
