### ISSUE TITLE
Add a way to add a title to the images

### ISSUE THREAD

**Issue by DeflateAwning** [formatc1702/WireViz#460]
Either a titleblock or a top-of-page title would be good.

If this does exist, it should be added to more examples.

**Comment by snelweg** [comment]
[Power supplies.pdf](https://github.com/user-attachments/files/19929206/Power.supplies.pdf)

You can use the `template` function for that? The title block only shows up in the .html file, but you could export that to a pdf and have the titleblock integrated.

``` yaml
metadata: &metadata 
  title: Power supplies
  pn: PSU

  authors:
    Created:
      name: xxx
      date: 2025-03-11
    Approved:
      name: xxx
      date: 2025-03-11

  revisions:
    A:
      name: xxx
      date: 2025-03-12
      changelog: updates]

  template:
    name: din-6771    
    sheetsize: A4
```

https://github.com/wireviz/WireViz/tree/master/src/wireviz/templates

[Power supplies.pdf](https://github.com/user-attachments/files/19929207/Power.supplies.pdf)
