### ISSUE TITLE
[Bug] Loops on connectors number vs list index issue

### ISSUE THREAD

**Issue by ryane67** [formatc1702/WireViz#465]
When using loops on connectors, the check to draw ensures the connector number is in the list, however when they are drawn, the connection between the points is made from what appears to be the list index and not by the pin number.

```
connectors:
  AP-DISCO:
    pins: [1]
    pinlabels: [GND_SW]
  APRS1-J281:
    pins: [0,1,2,3,4,5,8,9,10,11,12,13,14,15]
    pinlabels: [SHELL, CANHI, CANLO,CANTERM1, CANTERM2,IDSTRAP_1,IDSTRAP_4,PWRGND, ACFTPWR,TRIMIN1, TRIMIN2, TRIMOUT1, TRIMOUT2, APDISCO]
    <<: [*db15_m, *can_device]
    loops:
      - [4,5]
      - [5,8]
```

![Image](https://github.com/user-attachments/assets/13da514e-407c-4dc0-83a2-76b5ad3d907d)

The intent here would be to realistically use 3,4 and 5,8 as the loops however I used 4,5 when testing whether it would use the index of pins in the list to create the graph.
