### ISSUE TITLE
Single wire has no color

### ISSUE THREAD

**Issue by contecto-willem** [formatc1702/WireViz#467]
For example:

  W17:
    gauge: 0.75 mm2
    length: 0.6
    color: BK
    wirecount: 1

Will not render with the correct color

**Comment by kvid** [comment]
If you expect the wire color to be black in your use case, then it's a matter of understanding the difference between the `color` and `colors` attributes of a cable. Try e.g. this input:
```yaml
cables:
  W17:
    gauge: 0.75 mm2
    length: 0.6
    color: BK  # Optional cable jacket color
    wirecount: 1  # If unspecified, the number of entries in a list of wire attributes will be used
    colors: [PK]  # List of colors for each wire in the cable (one single wire entry in this case)
connections:
  - - W17  # The cable need to be included in at least one connection to be rendered
```
The result will be a single pink wire in an outer black jacket. See also how these attributes are used in [example 11](https://github.com/wireviz/WireViz/tree/v0.4.1/examples#example-11).
