### ISSUE TITLE
[feature] How to short multiple pins on one connector?

### ISSUE THREAD

**Issue by azivkovic3l** [formatc1702/WireViz#48]

**Comment by formatc1702** [comment]
There is primitive functionality to attach two pins of the same connector. Please see the end of this modified example:

```yaml
connectors:
  X1:
    type: D-Sub
    subtype: female
    pinout: [DCD, RX, TX, DTR, GND, DSR, RTS, CTS, RI]
  X2:
    type: Molex KK 254
    subtype: female
    pinout: [GND, RX, TX]

cables:
  W1:
    gauge: 0.25 mm2
    length: 0.2
    color_code: DIN
    wirecount: 3
    shield: true

connections:
  -
    - X1: [5,2,3]
    - W1: [1,2,3]
    - X2: [1,3,2]
  -
    - X1: 5
    - W1: s
  - # short pins 6,7,8 together
    - X1: [6,7]
    - X1: [7,8]
```

See the output below. It's not pretty, so I am open for suggestions on how to best visualize this. I guess there is also a difference between running a wire between two pins, and connectors that allow some other sort of shorting internally.

![test](https://user-images.githubusercontent.com/2447251/86153338-cef8e180-bb01-11ea-8d05-8d135baea311.png)

**Comment by quotschmacher** [comment]
maybe it would be necessary to specify a starting and ending angle and a width, so that the shortage can be shorter?

**Comment by azivkovic3l** [comment]
Thanks for quick reply,

Short term, it would be nice to include this option in examles so everibody
know about it.
Long term, consider shorter length of connection line.

Regards,
Aleksandar

**Comment by formatc1702** [comment]
Yes, I do agree the current implementation is ugly and missing information... any ideas and/or pull requests on this topic are welcome!

**Comment by quotschmacher** [comment]
my python is too weak to help i think.
what about a (overriding) color attribtue for the connection? overriding: override the cable color if a cable is used. and an array in preparation for multi-color wires.

`connections:
  - color: [RD]
    - Relais1: [6, 12, 18 ]
    - Relais1: [12, 18, 24]
`

**Comment by formatc1702** [comment]
Here's a mockup of what it could look like:
![IMG_3700](https://user-images.githubusercontent.com/2447251/87183014-91f0d400-c2e5-11ea-9e12-939116eceefa.JPG)

I'm not sure how easy that would be to represent graphically... I'll think about it.
A possible input syntax could be:
```yaml
connectors:
  X1:
    pinout: [...]
    internal_shorts:
      - [1,2]
      - [3,5,7]
      - [4,6]
```

The primitive example from my comment above, with external loops, could be solved in a similar way:

```yaml
connectors:
  X1:
    pinout: [...]
    external_shorts:
      - [6,7] # exactly 2 pins must be specified
      - [7,8]
```

Only thing missing is a bit of info on what kind of wire to use for the external shorts.

**Comment by azivkovic3l** [comment]
I need small help, I'm using your dev branch because of new features that are still not in master. I see that pins shorting feature is moved to version 0.3. Until than, dev branch complains with the following "Exception: X1 is not in cables" when I define that connector X1 must have shorted pins 3 and 10:
    - X1: [3,10]
    - X1: [10,3]

What is a new syntax for this shorting in dev branch?

**Comment by formatc1702** [comment]
Sorry for the super late reply!
In the newly released v0.2, try the following to short pins 3 and 10... it will be displayed as a wire loop between them, and you have no control over the wire appearance/properties, but maybe this helps you.

```
X1:
  # connector parameters
  loops:
    - [3, 10]
```

**Comment by dbozec** [comment]
Hi, I have a small issue with those loops.
On one of my project the loop wire is hidden behind the Wire description table next to the connector
![2022-08-23-180007_563x264_scrot](https://user-images.githubusercontent.com/2538020/186227836-83f1662f-6cec-4e14-9b74-68ad36b6cedb.png)
It's not really readable :(
```yaml
  -
    - P1: [1]
    - W1: [1]
    - P1: [9]
```
