### ISSUE TITLE
[feature] Ability to add BOM items within components

### ISSUE THREAD

**Issue by MikeCrookes** [formatc1702/WireViz#50]
Would be great to be able to specify the crimps for connectors and for this to be added to the BOM

**Comment by formatc1702** [comment]
This is a very good point, especially once you get to more complicated [mixed contact connectors](https://d-sub-connector.com/pages/combi-d-sub-connectors) (first example that come to mind) which need different crimp types within one connector.

Maybe @Tyler-Ward our BOM expert has a suggestion? 😃

**Comment by Tyler-Ward** [comment]
This sounds like a good idea and probably wouldn't be too hard to add. Doing #51 first sounds sensible and should be relatively easy to do.

I can see there being two methods to define the crimps.

For single crimp types a string can be set for the crimp part number and internal part number and used for all positions. (might want a flag to turn on/off limiting crimps to only being added for populated positions). With Templating this can allow the crimp to be declared for an entire series of connectors at once e.g. all female Molex KKs.

For multiple crimp types we can specify with arrays similar to bundle wires. Will likely also need a field for a crimp description so they can have a useful description in the bom. The array helper function in #62 will help for this. As well as the example above a common example of needing this might be where there are different crimp parts depending on wire gauge.

For interest If you want connectors with unusual loadouts I believe it is possible to set up some lemo connectors to have all of the following in one connector, Low voltage, high voltage, coax, fibre-optic and fluid/gas.

**Comment by formatc1702** [comment]
Do you want to take care of this? I'm starting to assign issues to contributors to keep an overview of what's going on, so let me know!

**Comment by Tyler-Ward** [comment]
I'm happy to take those on so feel free to assign to me.

**Comment by formatc1702** [comment]
Much appreciated. It seems you have to comment on #51 in order to be eligible for assigning.

**Comment by formatc1702** [comment]
An idea here would be to tag certain items to be used only for pins that are actually populated, others for all pins (qty = pincount), others in custom quantities (like you mentioned, backshells and the like)

**Comment by Tyler-Ward** [comment]
Apologies for the lack of progress on this the last couple of weeks have bee quite busy. rather than the implementation idea suggested above in https://github.com/formatc1702/WireViz/issues/50#issuecomment-653888954 integrating crimps into the idea from #51 which supports additional components on parts might be a better soloution rather than having two methods of defining.

I have created a potential format for describing these below. by specifying an additional item field a list of additional items can be added to a connector (or wire). For quantity this can either be a number, "pincount" for the number of pins in a connector or "connectioncount" for the number of connections used. To account for items where the connector is made up of constituent parts and doesnt have a main part (anderson powerpoles as an example) i have also added a ignore_in_bom field below that will prevent creation of a line for the connector itself. This might also be usefull for preterminated connectors which will curently generate two lines in the bom (one for the connector and one for the cable).

Any thoughts or suggestions on the format addition example below?

``` yaml
connectors:
  X1:
    type: Powerpole
    pinout: [GND, VCC]
    ignore_in_bom: true
    additional_components:
      -
        type: housing
        qty: 1
        unit: ea
        manufacturer: Anderson
        manufacturer_part_number: 1327G6
        internal_part_number: powerpole-black
      -
        type: housing
        qty: 1
        unit: ea
        manufacturer: Anderson
        manufacturer_part_number: 1327
        internal_part_number: powerpole-red
      -
        type: crimp
        qty: pincount
        unit: ea
        manufacturer: Anderson
        manufacturer_part_number: 1331
        internal_part_number: powerpole-crimp-30A
  X2:
    type: Molex Micro-Fit
    subtype: female
    pinout: [GND, VCC, A, B, C]
    manufacturer_part_number: 436450500
    manufacturer: Molex
    internal_part_number: MF3.0-5
    additional_components:
        type: crimp
        qty: connectioncount
        unit: ea
        manufacturer: Molex
        manufacturer_part_number: 43030-0007
        internal_part_number: MF3.0-Crimp

```
