### ISSUE TITLE
[feature] More control over wire parameters

### ISSUE THREAD

**Issue by Tyler-Ward** [formatc1702/WireViz#56]
Based on discussions in #11  it might be worth adding the ability alter more properties of individual wires in a cable or bundle e.g. guage (an example would be a usb cable with two thinner wires and two power wires). This will obviously add some additional complexity to both the definition format and to rendering cables/bundles with multiple parameters.

This feature could also allow for sub wires to be templated which will make reusing wires in multiple bundles or several times in the same bundle easier. A modified format concept from  #11 is shown below for reference.
``` yaml
templates:
  - &blueWire
    part_number: 12345
    color: BU

  W1:
    category: bundle
    length: 0.3
    wireinfo:
      1:
        part_number: 12344
        color: BK
      2: <<: &blueWire
      3: <<: &blueWire
      4:
        part_number: 12343
        color: WH
```

**Comment by formatc1702** [comment]
A simple solution might be to allow every parameter of the cable/bundle to be either a string / int (applying it to all wires) or a list (length = wirecount),similar to how e.g. part numbers for bundles are handled now. It would be slightly more concise, and, when formatted cleverly, easier to read?

```yaml
W1:
  category: bundle
  length: 0.3 # maybe even this could become a list? does it make sense?
  colors:                   [BK,    BU,    BU,    RD   ]
  gauge:                    [0.25,  0.25,  0.5,   0.5  ]
  manufacturer_part_number: [12344, 12345, 12346, 12343]
```

Templating would not be as easy, though. Just a thought.

**Comment by tim292stro** [comment]
Parameterizing is one of the major convenience factors of tools found in the commercial marketplace.  For example being able to say "This part" then have that part be defined by a separate drawing, which is then pulled in at compile time - allows for that to be a separate file even that can be managed separately.

Similarly, being able to do math in line on a parameter, allows for cases like "this branch needs to be 2/3 of the way along this trunk", where the trunk length is a variable and the Branch(Length) = Trunk(Length) * (2/3).  This way if the trunk length is changed, the branch length will be changed maintaining the ratio.

I think since this can become multi-dimensional, it's a good ideal to break this out earlier in a file as a general practice - much like doing "global defines".  When it gets down to a bundle, this would be an array or arrays, with each conductor definition being its own array of defined attributes inherited from the conductor definition.

**Comment by tim292stro** [comment]
I think this is also a suitable feature request to piggyback with another suggestion - that wire parameters not be limited to simply DC electrical characteristics.  Consider this type of cable:
![WR2R2C62FSJ_media-001](https://user-images.githubusercontent.com/45922790/86518850-9733b780-bde9-11ea-9643-54e77a6de5eb.jpg)
There is 2x Cat-6, 2x RG-6 RF, and 2x multimode fiber.

Or this example in robotics where it's not just Data+Power+light, but also air or hydraulic fluid being transmitted - and note that the "bundle" may not be is something like a split loom or brain - but a drag chain, or rigid conduit:
![HUBKELE01300_TWB_PE_001](https://user-images.githubusercontent.com/45922790/86518879-df52da00-bde9-11ea-8c45-9ec8678a9ec1.jpg)

**Comment by Tyler-Ward** [comment]
For including data/templates from a separate file it looks to be possible to add support for this in pyyaml https://stackoverflow.com/questions/528281/how-can-i-include-a-yaml-file-inside-another

**Comment by formatc1702** [comment]
It was added very discreetly and I haven't tested it, but at least running WireViz from CLI allows to include a 'prepend file' in addition to the source YAML ([see code](https://github.com/formatc1702/WireViz/blob/master/src/wireviz/wireviz.py#L219)).

I wouldn't want to mess too much with the pyyaml internals TBH, maybe this is a more reasonable approach?

**Comment by formatc1702** [comment]
Just a bit of brainstorming here.

We should look at this issue from two perspectives:

## 1. The internal data representation

It might make sense to shuffle around the representation of connectors and cables in the code, towards a more "object-oriented" approach, for lack of a better term.

Example (not intended to be complete, just to show my general idea):
```yaml
cable:
  name: ...
  category: ...
  type: ...
  show_equiv: ...
  ... # other global parameters
  wires:
    1: # unique internal auto-incremented number
      id: Wire1 # unique user-assigned ID
      label: VCC # arbitrary label
      length: 123
      gauge: 0.25 mm2
      color: 0xFF0000 # internal unambiguous color for rendering
      color_name: RD # user-visible color label
      ...
    2:
      ... # repeat
    ... # repeat
  additional_bom_items:
```
This nested hierarchy would allow a good degree of granularity for all kinds of parameters, and cleanly separate between user-assigned info (`id`,`label`,`color_name`) and internal info (the wire's dict key, `color`)...
This would get rid of having to rely on potentially ambiguous user-provided info, getting rid of #160 

## 2. The user input

For many cases, some parameters nested within each individual wire in the example above, will be identical for all wires in a cable/bundle. Therefore, it would be nice to keep the current syntax for these simple cases to avoid repetition:
```yaml
W1:
  gauge: 0.25mm2 # applies to all wires
  length: 1 m # applies to all wires
  colors: [RD, BK, ...] # gets split among all the wires
  ..
```
The question is how to expand this for cases where not all wires are identical.
1.  Use a column-based approach like the example in the [Jul 3 comment above](https://github.com/formatc1702/WireViz/issues/56#issuecomment-653388937)?
1. Use the same syntax as the internal representation?
  This would allow setting parameters *both* at the cable level, allowing the children (wires) to inherit the value, as well as overriding a parameter for individual wires where necessary.

Since the proposed internal representation would have all info split across all children (so as not to have to back-track to find inherited parameter values), it would be necessary to check at rendering time, whether a parameter (e.g. `length`) is equal for all children, and can thus be shown in the surrounding cable node, or if it differs from wire to wire, which would require showing the individual values next to the corresponding wires.

I am afraid that this would require a major refactoring, and perhaps it would be wise to issue a feature-freeze at some point to tackle this. I welcome any thoughts on this topic.
