### ISSUE TITLE
[internal] Make connecting components together easier and more flexible

### ISSUE THREAD

**Issue by formatc1702** [formatc1702/WireViz#67]
Inspired by discussions in #26 and #45 .

- Make it easier to define `cable-connector-cable` type connections to make creating [this](https://github.com/formatc1702/WireViz/issues/45#issuecomment-654352415) kind of layouts easier.
  Currently supported connections are `con-cbl-con`, `con-cbl` and `cbl-con`,
  as well as `ferrule-cable` and `cable-ferrule` with ferrule auto-generation.
  Relevant code is [here](https://github.com/formatc1702/WireViz/blob/dev/src/wireviz/wireviz.py#L94L194).
- With some clever coding, maybe even arbitrarily long connection sets could be defined, e.g. `connector-cable-connector-cable-ferrules`
- Allow ferrule-type connectors to have (and show) designators, and include these in the BOM, if visible.
  But probably hide ferrule designators by default.
- Generalize `ferrule` category to `simple`(=only one port/pin, easy to auto-generate if designators are not important)

**Comment by formatc1702** [comment]
The goal is to generate e.g. this output:
![test](https://user-images.githubusercontent.com/2447251/86618809-d1ec4a00-bfb9-11ea-82ea-9acdf7051459.png)
from something like this:
```yaml
connections:
  - 
    - C1: [1-3]
    - [S1, S2, S3] # Wago's need pre-defined designators so they can be referre to later on
    - C3: [1-3]
  -
    - C2: [1-3]
    - [S1, S2, S3] # join a new cable with the existing Wago's
```
