### ISSUE TITLE
[bug] fix issue when hiding both name and wirecount of a cable/bundle with no further attributes

### ISSUE THREAD

**Issue by formatc1702** [formatc1702/WireViz#69]

**Comment by kvid** [comment]
Please include a YAML file here that demonstrates the bug. That would make it easier to verify the fix, and it should be included in the corner cases described in issue #63.

**Comment by formatc1702** [comment]
```yaml
connectors:
  X1:
    type: D-Sub
    subtype: female
    pincount: 9
  X2:
    type: Molex KK 254
    subtype: female
    pincount: 3

cables:
  W1:
    wirecount: 3
    show_name: false
    show_wirecount: false
    # shield: true

connections:
  -
    - X1: [5,2,3]
    - W1: [1,2,3]
    - X2: [1,3,2]
```
