### ISSUE TITLE
Question: Connector Paths

### ISSUE THREAD

**Issue by sahil48** [formatc1702/WireViz#81]
Using Demo 02 in the readme as a starting point and focusing on X2, it is possible to show the black and red wire going from X1 to X2, and the yellow and green wire going from X2 to X3?

Basically, if there are wires from X1 to X2, can there also be wires from X2 to X3 or from X2 to a completely different connector?

**Comment by formatc1702** [comment]
It is possible, of course, but the output might not look like you expect, since the diagram is always drawn from left to right.

The reason is partly due to the WireViz structure (connector-cable-connector), partly due to the underlying GraphViz rendering engine.

I'm unsure whether this is your intent, but here's an example of how your question might be realized. Note the comments.
Note that the weird bend in W2's black wire comes from the GraphViz engine and is thus something WireViz has little control over.

![test](https://user-images.githubusercontent.com/2447251/87331275-002dd480-c53a-11ea-8955-956d7e741fc9.png)

```yaml
templates: # defining templates to be used later on
  - &molex_f
    type: Molex KK 254
    subtype: female
  - &con_i2c
    pinout: [GND, +5V, SCL, SDA]
  - &wire_i2c
    category: bundle
    gauge: 0.14 mm2
    colors: [BK, RD, YE, GN]

connectors:
  X1:
    <<: *molex_f # copying items from the template
    pinout: [GND, +5V, SCL, SDA, MISO, MOSI, SCK, N/C]
  X2:
    <<: *molex_f
    <<: *con_i2c # it is possible to copy from more than one template
  X3:
    <<: *molex_f
    <<: *con_i2c
  X4:
    <<: *molex_f
    pinout: [GND, +12V, MISO, MOSI, SCK]
  ferrule_crimp:
    category: ferrule
    autogenerate: true
    type: Crimp ferrule
    subtype: 0.25 mm²

cables:
  W1:  # modified for example
    category: bundle
    gauge: 0.14 mm2
    colors: [BK, RD]
    length: 0.2
    show_equiv: true
  W2:
    <<: *wire_i2c
    length: 0.4
    show_equiv: true
  W3:
    category: bundle
    gauge: 0.14 mm2
    length: 0.3
    colors: [BK, BU, OG, VT]
    show_equiv: true
  W4:
    gauge: 0.25 mm2
    length: 0.3
    colors: [BK, RD]
    show_equiv: true
  W5:  # added for example
    gauge: 0.14 mm2
    colors: [YE, GN]
    length: 0.4
    show_equiv: true

connections:
  -  # modified for example
    - X1: [1-2]
    - W1: [1-2]
    - X2: [1-2]
  -
    - X1: [1-4]
    - W2: [1-4]
    - X3: [1-4]
  -
    - X1: [1,5-7]
    - W3: [1-4]
    - X4: [1,3-5]
  -
    - ferrule_crimp
    - W4: [1,2]
  -
    - W4: [1,2]
    - X4: [1,2]
  -  # added for example
    - X2: [3-4]
    - W5: [1-2]
    - X3: [3-4]
```
