### ISSUE TITLE
[bug] \n Displayed in Cable Notes

### ISSUE THREAD

**Issue by davidrea** [formatc1702/WireViz#86]
Adding a `\n` escaped character works to insert a line break in:

* Connector `notes:` entities
* Connector `type:` and `subtype:` entities

But the `\n` escaped character is printed in cable `notes:` entities:

![image](https://user-images.githubusercontent.com/229141/87438489-97883b80-c5bd-11ea-93e7-d96805ce0ba1.png)

Source for above:

```yml
connectors:

  P1:
    type: Socket housing
    subtype: Molex SL\n50579406
    pinout: [VDD, SWCLK, GND, SWDIO, NRST, SWO]
    notes: "Terminal: 16020086 or equiv."

  P2:
    type: Pin header
    subtype: Adam Tech\nBHR-20-VUA\nor Equiv.
    pinout: [VCC, VCC (optional), TRST, GND, TDI, GND, DIO/TMS, GND, DCK/TCK, GND, RTCK, GND, SWO/TDO, GND, NRST, GND, NC, GND, NC, GND]
    notes: Solder wires to pins,\nheat shrink individually

cables:
  W1:
    gauge: 24 AWG
    length: 0.2
    wirecount: 6
    category: bundle
    colors: [RD, GY, BK, GY, GY, GY]
    notes: Stranded,\nHeat shrink bundle 2 plcs
    # ^^^ this line contains printed \n ^^^

connections:
  -
    - P1: [1, 2, 3, 4, 5, 6]
    - W1: [1, 2, 3, 4, 5, 6]
    - P2: [1, 9, 4, 7, 15, 13]
```

**Comment by davidrea** [comment]
Just tacking onto this, \n escaped characters also appear in HTML BOM:

![image](https://user-images.githubusercontent.com/229141/87444466-d53c9280-c5c4-11ea-9fde-8dd7d924ce7b.png)

**Comment by formatc1702** [comment]
Thanks for the heads up. I can't look at the issue in detail now, but I can offer solution that (IMHO) is more elegant than using `\n` for new lines, since [YAML supports multiline strings natively](https://yaml-multiline.info/).
The code below fixes both the rendering and BOM issues:

```yaml
connectors:
  P1:
    type: Socket housing
    subtype: |
      Molex SL
      50579406
    pinout: [VDD, SWCLK, GND, SWDIO, NRST, SWO]
    notes: "Terminal: 16020086 or equiv."

  P2:
    type: Pin header
    subtype: |
      Adam Tech
      BHR-20-VUA
      or Equiv.
    pinout: [VCC, VCC (optional), TRST, GND, TDI, GND, DIO/TMS, GND, DCK/TCK, GND, RTCK, GND, SWO/TDO, GND, NRST, GND, NC, GND, NC, GND]
    notes: |
      Solder wires to pins,
      heat shrink individually

cables:
  W1:
    gauge: 24 AWG
    length: 0.2
    wirecount: 6
    category: bundle
    colors: [RD, GY, BK, GY, GY, GY]
    notes: |
      Stranded,
      Heat shrink bundle 2 plcs

connections:
  -
    - P1: [1, 2, 3, 4, 5, 6]
    - W1: [1, 2, 3, 4, 5, 6]
    - P2: [1, 9, 4, 7, 15, 13]
```

I will still keep this open, but I'm unsure whether converting `\n` to newline is something that should be implemented if there is a more standard way in YAML.
